config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'projects', to: 'pages#projects'
  get 'team', to: 'pages#team'
  get 'clients', to: 'pages#clients'
  post 'team', to: 'team#create'
  post 'projects', to: 'projects#create'
  post 'clients', to: 'clients#create'
  post '', to: 'home#create'

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  resources :cats
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/test_email_form.rb
class TestEmailForm < MailForm::Base
  attribute :fullname, validate: true
  attribute :email, validate: /\A[^@\s]+@[^@\s]+\z/i
  attribute :phonenumber


  attribute :message
  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      subject: "My Contact Form",
      to: "ttatsianatt@gmail.com",
      from: %("#{fullname}" <#{email}>)
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :set_locale_from_domain

  private
  def set_locale
    I18n.locale = extract_locale_from_tld || I18n.default_locale
  end

  def extract_locale_from_tld
    parsed_locale = request.host.split('.').last
    I18n.available_locales.map(&:to_s).include?(parsed_locale)? parsed_locale : nil
  end

  def set_locale_from_domain
    detected_locale = Rails.application.config.hosts.key(request.host)
    I18n.locale = I18n.available_locales.map(&:to_s).include?(detected_locale) ?
    detected_locale : I18n.default_locale
  end

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
  end

  def show
  end


  def create
    @message = params[:message]
    @fullname = params[:fullname]
    @email = params[:email]
    @phonenumber = params[:phonenumber]
    puts @message, @fullname, @email, @phonenumber
    c = TestEmailForm.new(fullname: @fullname, email: @email, message: @message, phonenumber: @phonenumber)
    c.deliver

    redirect_to root_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def show
  end

  def create
    @message = params[:message]
    @fullname = params[:fullname]
    @email = params[:email]
    @phonenumber = params[:phonenumber]
    puts @message, @fullname, @email, @phonenumber

    c = TestEmailForm.new(fullname: @fullname, email: @email, message: @message, phonenumber: @phonenumber)
    c.deliver

    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def projects
  end

  def team
  end

  def clients
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
  end

  def show
  end

  def create
    @message = params[:message]
    @fullname = params[:fullname]
    @email = params[:email]
    @phonenumber = params[:phonenumber]
    puts @message, @fullname, @email, @phonenumber

    c = TestEmailForm.new(fullname: @fullname, email: @email, message: @message, phonenumber: @phonenumber)
    c.deliver

    redirect_to root_path
  end
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  def index
  end

  def show
  end

  def create
    @message = params[:message]
    @fullname = params[:fullname]
    @email = params[:email]
    @phonenumber = params[:phonenumber]
    puts @message, @fullname, @email, @phonenumber

    c = TestEmailForm.new(fullname: @fullname, email: @email, message: @message, phonenumber: @phonenumber)
    c.deliver

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag %>
    <title>StellaPartners</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
    <%= yield %>

  <%= render 'shared/footer' %>

  <script type="text/javascript">window.$crisp=[];window.CRISP_WEBSITE_ID="48950115-f49a-4215-bde7-67492fb5ee05";(function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();</script>

  </body>
</html>

app/views/pages/clients.html.erb
<div class="card-product">
  <%= image_tag 'client.jpg' %>
  <div class="card-product-infos">
    <h2>Client's name</h2>
    <p>Client description with <strong>relevant info</strong> only.</p>
  </div>
</div>
<div class="card-product">
  <%= image_tag 'client.jpg' %>
  <div class="card-product-infos">
    <h2>Client's name</h2>
    <p>Client description with <strong>relevant info</strong> only.</p>
  </div>
</div>
<div class="card-product">
  <%= image_tag 'client.jpg' %>
  <div class="card-product-infos">
    <h2>Client's name</h2>
    <p>Client description with <strong>relevant info</strong> only.</p>
  </div>
</div>

app/views/pages/home.html.erb
<div class="background" style="background-image: url('<%= image_path "background1.jpg" %>');">
</div>

app/views/pages/projects.html.erb
<div class="cards">
  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
    <h1>Project 1<h1>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
    <h1>Project 2<h1>
  </div>

  <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/dinner.jpg)">
    <h1>Project 3</h1>
  </div>
</div>

app/views/pages/team.html.erb
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
       <%= image_tag 'team1.jpg', class: 'd-block w-100', alt: 'first-slide', style: "width:100%; height:500px;" %>
        <div class="carousel-caption d-none d-md-block">
          <h5>Full name</h5>
          <p>Bio: Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'team2.jpg', class: 'd-block w-100', alt: 'first-slide', style: "width:100%; height:500px;" %>
        <div class="carousel-caption d-none d-md-block">
          <h5>Full name</h5>
          <p>Bio: Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
    </div>
    <div class="carousel-item">
      <%= image_tag 'team3.jpg', class: 'd-block w-100', alt: 'first-slide', style: "width:100%; height:500px;" %>
        <div class="carousel-caption d-none d-md-block">
          <h5>Full name</h5>
          <p>Bio: Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Our office:
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.jpeg" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "lang", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "English", "#", class: "dropdown-item" %>
              <%= link_to "Spanish", "#", class: "dropdown-item" %>
              <%#= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
             <li class="nav-item active">
            <%= link_to "Who we are", team_path, class: "nav-link who" %>
          </li>
          <li class="nav-item">
            <%= link_to "Recent projects", projects_path, class: "nav-link recent" %>
          </li>
          <li class="nav-item">
            <%= link_to "Clients", clients_path, class: "nav-link clients" %>
          </li>
          <li>
            <%= link_to "Contact", "#", class: "btn btn-primary btn-position-form", data: {toggle: "modal", target:"#exampleModal"} %>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
          <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel"><strong>How can we help?</strong></h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body">
                <%= form_with url: "/send", method: :get do |form| %>
                <%= form.label :message, "Your message:" %>
                <%= form.text_area :message, size: "50x2", class: "text-area p-2", value: " "%>
                <%= form.label :fullname, "Full name:" %>
                <%= form.text_area :fullname, size: "50x2", class: "text-area p-2", value: " "%>
                <%= form.label :email, "Email:" %>
                <%= form.email_field :email, size: "50X2", class: "text-area p-2", value: " " %>
                <%= form.label :phonenumber, "Phone number:" %>
                <%= form.phone_field :phonenumber, size: "50x2", class: "text-area p-2", value: " " %>
                <% end %>
                <p><em>Thank you for your message.</em></p>
              </div>
              <div class="modal-footer">
                <%= link_to "Send", "#", data: { confirm: 'We received your message' }, method: :post, class:"btn btn-secondary", 'data-dismiss': "modal" %>
                <%# <button type="button" class="btn btn-secondary" data-dismiss="modal">Envoyer</button> %>
                <%# <button type="button" class="btn btn-primary btn-pink">Retour</button> %>
              </div>
            </div>
          </div>
      </ul>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>